config/routes.rb
Rails.application.routes.draw do

  resources :employees do
    collection {post :import}
  end
  resources :companies do
    collection {post :import}
  end
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  get 'welcome/pricing'

  get 'welcome/features'



  resources :invoices do
    resources :purchases, except: [:index], controller: 'invoices/purchases'
  end
 root to: 'welcome#index'
end

app/models/employee.rb
class Employee < ActiveRecord::Base

 def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Employee.create! row.to_hash
    end
  end
   def self.to_csv
      CSV.generate do |csv|
        csv<< column_names
        all.each do |employee|
          csv << employee.attributes.values_at(*column_names)
        end
       end
      end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json


  def index
    @employees = Employee.all

    respond_to do |format|
      format.html
      format.csv{render text: @employees.to_csv}
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Employee.import(params[:file])
      redirect_to employees_path, notice: "Employees Added Successfully"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :phone_number, :job)
    end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="control-group">
    <%= f.label :name, class: 'control-label' %><br>
        <div class="control">
    <%= f.text_field :name %>
      </div>
  </div>
    <div class="control-group">
    <%= f.label :phone_number, class: 'control-label' %><br>
        <div class="control">
    <%= f.text_field :phone_number %>
      </div>
  </div>
    <div class="control-group">
    <%= f.label :job, class: 'control-label' %><br>
        <div class="control">
    <%= f.text_field :job %>
      </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>
<div class="media">
   <div class="media-body">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>Job</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.name %></td>
              <td><%= employee.phone_number %></td>
              <td><%= employee.job %></td>
              <td><%= link_to 'Show', employee, class:'btn btn-mini default'%></td>
              <td><%= link_to 'Edit', edit_employee_path(employee), class:'btn btn-mini btn-success' %></td>
              <td><%= link_to 'Destroy', employee, method: :delete, class:'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
</div>
      <br>

          <h3>Import Employees File</h3>
              <%= form_tag import_employees_path, multipart: true do %>
              <%= file_field_tag :file %>
              <%= submit_tag "Upload Employees", class: 'btn btn-default' %>
          <% end %>
          <h3>Download File</h3>
              <%= link_to "Report", employees_path(format: "csv"), class: 'btn btn-default' %>
       <br>
             <br>
      <%= link_to 'New Employee', new_employee_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone_number %>
</p>

<p>
  <strong>Job:</strong>
  <%= @employee.job %>
</p>



<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>